### ISSUE TITLE
name 'UnsupervisedDataBunch' is not defined

### ISSUE THREAD

**Issue by codechrl** [kireygroup/fastsom#12]
by following examples on link:
[https://kireygroup.github.io/fastsom/examples/colors.html#Creating-the-DataBunch](url)

on cells 4:
`db = UnsupervisedDataBunch(x, valid=0.05, sampler='shuffle', bs=50)`

i got error saying:

> name 'UnsupervisedDataBunch' is not defined

**Comment by rsayn** [comment]
Hi, we're having an issue in CI and the documentation website is not being updated.
You should refer to the [notebooks folder](https://github.com/kireygroup/fastsom/tree/master/nbs) in this repository for usage examples.
