### ISSUE TITLE
How to get the trained model?

### ISSUE THREAD

**Issue by catweis** [kireygroup/fastsom#14]
Hello,
first of all, thank you very much for this very easy and fast SOM-implementation. I just have tested it in comparison to other SOMs and it is impressively fast. And there was no GPU involved!
My question is how to get the trained model afterward? I want to train a model for a huge dataset and then apply it to another one. Therefore, I would need to access the model.
Sorry if this is in the documentation, but I have not found it, yet.
With kind regards

**Comment by rsayn** [comment]
Hello,
once you have trained a SomLearner with your data, you can access the model with the `learn.model` parameter: this is the instance of the [Som class](https://github.com/kireygroup/fastsom/blob/master/fastsom/som/som.py), which is a Pytorch model.

Anyway, if your goal is to predict data from another dataset, you can use the `SomLearner` directly as follows:
```python
df = pd.read_csv(...) # the dataset you want to use for prediction
test_dl = learn.dls.test_dl(df) # this will apply the same preprocessing that was used to create the Learner to your new data
preds, _ = learn.dls.get_preds(dl=test_dl)
```

Unfortunately there's an issue with Github Actions that's preventing the documentation from being updated correctly, but you can refer to [these notebooks](https://github.com/kireygroup/fastsom/tree/master/nbs) for more examples.
The last cell of the [House Price notebook](https://github.com/kireygroup/fastsom/blob/master/nbs/house-prices.ipynb) in particular shows how to run predictions on a Fastai Learner. This is not a SomLearner, however the API is the same.

I hope this helps, let me know if you have more questions 😄

**Comment by catweis** [comment]
Thank you very much for your fast and kind response.  I now know how to get the model
Unfortunately, your example does not work. It gives the following lines of code:

Traceback (most recent call last):
  File "<input>", line 2, in <module>
  File "E:\\venv1\lib\site-packages\fastcore\basics.py", line 388, in __getattr__
    if attr is not None: return getattr(attr,k)
  File "E:\\venv1\lib\site-packages\fastcore\basics.py", line 388, in __getattr__
    if attr is not None: return getattr(attr,k)
  File "E:\\venv1\lib\site-packages\fastcore\basics.py", line 388, in __getattr__
    if attr is not None: return getattr(attr,k)
  File "E:\\venv1\lib\site-packages\fastcore\transform.py", line 202, in __getattr__
    def __getattr__(self,k): return gather_attrs(self, k, 'fs')
  File "E:\\venv1\lib\site-packages\fastcore\transform.py", line 165, in gather_attrs
    if not res: raise AttributeError(k)
AttributeError: get_preds
test_dl = learn.dls.test_dl(df)
test_dl
<fastai.tabular.core.TabDataLoader object at 0x0000023A9E0A8D88>

**Comment by rsayn** [comment]
My bad, the last line I gave you is wrong. It should be:
```python
preds, _ = learn.get_preds(dl=test_dl)
```

**Comment by catweis** [comment]
Thank you very much! Now it works fine.
