### ISSUE TITLE
Cosine distance

### ISSUE THREAD

**Issue by claudiobottari** [kireygroup/fastsom#2]
It would be nice to have the cosine distance implemented to test it on embeddings

**Comment by rsayn** [comment]
A first implementation is available in the [latest commit](https://github.com/kireygroup/fastsom/commit/66c6213d8a1b98df212c797d716757352dd16bb4).
The `grouped_distance` function can be used in combination with `pcosdist` to compute embedding distance. Currently, it only works with fixed-size embeddings when the whole dataset is made of embedding vectors, but this implementation can serve as a template for more specific/complex use cases.

**Comment by rsayn** [comment]
The `datasets` API was reworked in v0.1.8 to leverage the `fastai.tabular` package.
A `Vectorize` processing step has been added, together with `MixedEmbeddingDistance` that uses cosine distance under the hood.

`Vectorize` can be found [here](https://github.com/kireygroup/fastsom/blob/64a5cff657cbb6813afa69fcfb033ed58ff64cec/fastsom/data_block/transform.py#L111), and an example notebook on House Prices using embeddings can be found [here](https://github.com/kireygroup/fastsom/blob/64a5cff657cbb6813afa69fcfb033ed58ff64cec/nbs/house-prices.ipynb).
