### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by SeanPedersen** [kireygroup/fastsom#7]
Hey man,
cool project! Looked at first sight really promising but the example (https://kireygroup.github.io/fastsom/examples/iris.html) is just not working....

I installed via pip: `pip install -qq fastsom`

`db = UnsupervisedDataBunch((x, y), valid=0.05, sampler='shuffle', normalizer='var', bs=50)`
Throws an import error.

Would relly like to give this lib a shot but need some working examples... hope it is no big issue so it can be easily resolved.

**Comment by rsayn** [comment]
Hello!
You can refer to [this notebook](https://github.com/kireygroup/fastsom/blob/master/nbs/iris.ipynb) for a working example, or more in general to the [notebooks folder](https://github.com/kireygroup/fastsom/blob/master/nbs) here on the repo. Seems the example notebook you linked refers to an older API from last year, I will look into that.

In case you have further issues, please make sure you are using the correct version of Fastai: this project was implemented using with Fastai 1.0.60, but for some reason pip seems to like installing version 2 instead (see #4 ).

In the upcoming weeks I'm looking forward to updating the repository to Fastai version 2.

**Comment by SeanPedersen** [comment]
Thanks for the quick response.
Your linked notebook works somewhat better!
My FastAI version is: 1.0.60

`learn = SomLearner(data, size=(8, 8), visualize=['weights'])`
prints: TEST

`learn.fit(50)`
executes but throws an error at the very end:
```
/usr/local/lib/python3.6/dist-packages/fastsom/interp/metrics.py in mean_quantization_err(pred_b, yb, som)
     76     row_sz = som.size[0]
     77     preds = idxs_2d_to_1d(pred_b, row_sz)
---> 78     return pdist(xb, w[preds], p=2).mean()
     79 
     80 

IndexError: tensors used as indices must be long, byte or bool tensors
```

```
%matplotlib inline
interp.show_hitmap()
```
Throws a similar error:```

/usr/local/lib/python3.6/dist-packages/fastsom/interp/interp.py in show_hitmap(self, save)
     93         z = torch.zeros(self.learn.model.size[:-1]).long()
     94         for i, c in enumerate(out):
---> 95             z[c[0], c[1]] += counts[i]
     96 
     97         sns.heatmap(z.cpu().numpy(), linewidth=0.5, annot=True, ax=ax, fmt='d')

IndexError: tensors used as indices must be long, byte or bool tensors
```

The rest of the notebook is working. Hope this will help you resolve all issues.

**Comment by rsayn** [comment]
These look like issues introduced by changes in newer versions of PyTorch.

I wasn't able to reproduce this behavior on my local machine; it would help if you could provide the following information:

 - The version of PyTorch you're currently running
 - The output of the following code:
 
 ```python
sample_in = torch.randn(64, 4) # assuming you're using the iris notebook, which has 4 features
sample_in = sample_in.cuda()   # or .cpu() in case you're training on cpu
sample_out = learn.model.forward(sample_in)

print(sample_out)
```

**Comment by SeanPedersen** [comment]
I am testing on Google Colab Jupyter Notebook.

It is running PyTorch version:
`1.7.0+cu101`

```
sample_in = torch.randn(4, 4) # assuming you're using the iris notebook, which has 4 features
sample_in = sample_in.cpu()   # or .cpu() in case you're training on cpu
sample_out = learn.model.forward(sample_in)

print(sample_out)
```
works as expected:
```
tensor([[ 7.6875, 11.0000],
        [15.3125,  5.0000],
        [11.4375,  7.0000],
        [ 2.6875, 11.0000]])
```

**Comment by rsayn** [comment]
Actually, the output to the `som.forward` should be a `LongTensor` (indices of best-matching point in the map), while in your case it appears to be a `FloatTensor`.
This is weird, I'll try creating a fresh environment with PyTorch 1.7.0 and see if I can reproduce this.

**Comment by SeanPedersen** [comment]
Yes I would recommend upgrading to latest PyTorch version for this project.

**Comment by rsayn** [comment]
Yeah, as I said it is probably due to some incompatibility with the version of PyTorch you're using, since I tried this on both versions `1.6.0` and `1.7.1` (which I had ready on my machine) and both seem to be fine.

I should be able to test version `1.7.0` tomorrow; if that's the problem I will lock PyTorch to version 1.7.1 in the setup file.

**Comment by rsayn** [comment]
I was able to reproduce the issue. It was caused by PyTorch no longer returning a `LongTensor` when dividing two `LongTensor`s with the true divide (`/`) operator; newer versions require an explicit integer divide (`//`) operator.
